# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage1
    jobs:
      - job: 
        steps:
          - script: echo stage 1      
  - stage: stage2
    jobs:
      - job: 
        steps:
          - script: echo stage 2
  - stage: stage3
    dependsOn: stage1
    jobs:
      - job: 
        steps:
          - script: echo stage 3